# Configuración del análisis
# Modificar con cuidado: estos parámetros condicionan todos los notebooks

project:
  name: tfm-ras
  seed: 42

family:
  name: RAS
  members:
    KRAS:
      uniprot_id: P01116
      isoform: P01116-1
      length: 189
      domain_g:
        start: 1
        end: 166
      pdbs:
        primary:
          id: 4OBE
          ligand: GDP
          resolution_angstrom: 1.24
        secondary:
          id: 5UK9
          ligand: GppNHp
          resolution_angstrom: 1.89
    HRAS:
      uniprot_id: P01112
      length: 189
      domain_g:
        start: 1
        end: 166
      pdbs:
        primary:
          id: 3K8Y
          ligand: GppNHp
          resolution_angstrom: 1.30
        secondary:
          id: 2RGE
          ligand: GDP
          resolution_angstrom: 1.40
    NRAS:
      uniprot_id: P01111
      length: 189
      domain_g:
        start: 1
        end: 166
      pdbs:
        primary:
          id: 5UHV
          ligand: GppNHp
          resolution_angstrom: 1.67
        secondary:
          id: 3CON
          ligand: GDP
          resolution_angstrom: 1.65

active_site:
  numbering: shared_uniprot
  regions:
    p_loop:
      start: 10
      end: 17
    switch_i:
      start: 30
      end: 38
    switch_ii:
      start: 60
      end: 76
    nkxd:
      start: 116
      end: 119
    sak:
      start: 145
      end: 147
  cofactors:
    - Mg2+

hotspots:
  - position: 12
    residue: G
  - position: 13
    residue: G
  - position: 61
    residue: Q
  - position: 146
    residue: A
  - position: 117
    residue: K
  - position: 59
    residue: A


thresholds:
  recurrent_min_members: 2
  recurrent_min_samples_per_member: 10

cosmic:
  version: "v104"        # Rellenar con la versión exacta usada (ej. "v100")
  human_reference_genome: "GRCh38"  # Rellenar con la referencia exacta usada (ej. "GRCh37" o "GRCh38")
  
  raw_filename: "Cosmic_MutantCensus_{version}_{human_reference_genome}.tsv.gz"
  classification_filename: "Cosmic_Classification_{version}_{human_reference_genome}.tsv.gz"

  example_filename: "cosmic_minimal_example.tsv"
  
  filters:
    somatic_status: "Confirmed somatic variant"
    mutation_description_contains: "missense_variant"
    deduplicate_by:
      - "COSMIC_SAMPLE_ID"
      - "MUTATION_AA"

paths:
  data_raw: "data/raw"
  data_example: "data/example"
  data_processed: "data/processed"
  data_external: "data/external"
  figures: "figures"